### ISSUE TITLE
Fix for flickering window

### ISSUE THREAD

**Issue by gijs-pennings** [BeLuckyDaf/snakes-game-tutorial#1]
For me, the window flickers quite intensely, to the point where it really bothered me. I was able to fix this by simply changing the superclass of `SnakeCanvas` from `Canvas` to `JPanel` as described [here](https://stackoverflow.com/a/11671311).

(If you want, I could open a pull request for this. Note that I did not test this change thoroughly at all, so I don't know if it causes any new issues.)

**Comment by ljonata** [comment]
Thanks for the suggestion.
